### ISSUE TITLE
[Bookworm] issue when loading a config file (.cube, .ovpn, .conf). Output: `Error: Unsupported image type : application/json`

### ISSUE THREAD

**Issue by sankayop** [labriqueinternet/vpnclient_ynh#131]
### Describe the bug

After a clean install of yunohost bookworm, I've installed the app vpnClient and tried to load a `neutrinet.cube` file.
Unfortunately, it stops with the error: `Error: Unsupported image type : application/json`.
This happens from both the GUI and CI interface. Also with `.ovpn` or `.conf` file extensions.

### Context

- Hardware: computer
- YunoHost version: 12.0.4.1 (testing)
- I have access to my server: Through SSH and through the webadmin
- App: VPN Client, version: 2.2~ynh5

### Steps to reproduce
```
sudo yunohost app config set vpnclient
```

### Expected behavior

```
========================================
>>>> Auto-configuration
========================================
Info: The VPN is not enabled
Enable VPN [yes | no]: yes
Info: VPNclient only interfaces with *dedicated, public IP VPNs accepting inbound traffic*, preferably with an associated `.cube` (or `.ovpn/.conf`) configuration file. Checkout the [list of known compatible providers](https://yunohost.org/providers/vpn) for more info.
Configuration file: /home/user1/ovpn/neutrinet.cube
Warning: unable to retrieve string to translate with key 'Unsupported image type : application/json' for default locale 'locales/en.json' file (don't panic this is just a warning)
Error: Unsupported image type : application/json
Configuration file:                      
```

### Logs
https://paste.yunohost.org/ucozajivaz
(but nothing to be seen)

### Note:
Perhaps related, another issue: https://github.com/YunoHost/issues/issues/2462

**Comment by alexAubin** [comment]
Indeed :+1:  Should be fixed by : https://github.com/YunoHost-Apps/vpnclient_ynh/pull/132

**Comment by Lab-8916100448256** [comment]
Well, actually that PR was a work in progress. It does not fully fix the issue. I still don't understand fully what needs to be done to fix this
